sudo: false
language: ruby
rvm:
  - 2.3.1
  - jruby
  - rbx-2
before_install: gem install bundler -v 1.12.5
script: bundle exec rspec spec
notifications:
  email:
    recipients:
      - wootaw@gmail.com
    on_failure: change
    on_success: never
addons:
  code_climate:
    repo_token: fb779cb868a2fd4ecb41df8db0e57472f977682ca9ac7e85ac63e9bdd79a0032
