sudo: false
language: ruby
rvm:
  - 2.3.1
  - 2.4.0
before_install: gem install bundler -v 1.12.5
script: bundle exec rspec spec
notifications:
  email:
    recipients:
      - wootaw@gmail.com
    on_failure: change
    on_success: never
addons:
  code_climate:
    repo_token: 7fedad134e1b7d283411989b2063972bb9fada64a076b9a2a6bf6c523baa4057
